import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export function generateReport(result, resumeId) {
  const doc = new jsPDF();

  // ===== Header =====

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("AI Resume Analysis Report", 105, 17, {
    align: "center",
  });

  // ===== Reset Color =====

  doc.setTextColor(0, 0, 0);

  let y = 40;

  doc.setFontSize(12);

  doc.text(`Resume ID : ${resumeId}`, 15, y);

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    120,
    y
  );

  y += 12;

  // ===== ATS Score =====

  doc.setFillColor(220, 240, 255);

  doc.roundedRect(15, y, 180, 25, 3, 3, "F");

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  doc.text(
    `ATS Score : ${result.similarity_score}%`,
    105,
    y + 15,
    {
      align: "center",
    }
  );

  y += 40;

  // ===== Matched Skills =====

  doc.setFontSize(15);

  doc.text("Matched Skills", 15, y);

  y += 5;

  autoTable(doc, {
    startY: y,
    head: [["Skill"]],
    body: result.matched_skills.map((s) => [s]),
    headStyles: {
      fillColor: [34, 197, 94],
    },
  });

  y = doc.lastAutoTable.finalY + 10;

  // ===== Missing Skills =====

  doc.setFontSize(15);

  doc.text("Missing Skills", 15, y);

  autoTable(doc, {
    startY: y + 5,
    head: [["Skill"]],
    body: result.missing_skills.map((s) => [s]),
    headStyles: {
      fillColor: [239, 68, 68],
    },
  });

  y = doc.lastAutoTable.finalY + 12;

  // ===== AI Feedback =====

  doc.setFontSize(15);

  doc.text("AI Feedback", 15, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const feedback = doc.splitTextToSize(
    result.ai_feedback,
    180
  );

  doc.text(feedback, 15, y);

  // ===== Footer =====

  const pageHeight = doc.internal.pageSize.height;

  doc.setDrawColor(180);

  doc.line(15, pageHeight - 18, 195, pageHeight - 18);

  doc.setFontSize(10);

  doc.text(
    "Generated by AI Resume Analyzer",
    105,
    pageHeight - 10,
    {
      align: "center",
    }
  );

  doc.save("AI_Resume_Report.pdf");
}