import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export function generateReport(result, resumeId) {
  const doc = new jsPDF();

  // ==========================
  // Header
  // ==========================

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text(
    "AI Resume Analysis Report",
    105,
    17,
    { align: "center" }
  );

  doc.setTextColor(0, 0, 0);

  let y = 40;

  doc.setFontSize(11);

  doc.text(
    `Resume ID : ${resumeId}`,
    15,
    y
  );

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    110,
    y
  );

  y += 15;

  // ==========================
  // ATS Score
  // ==========================

  doc.setFillColor(219, 234, 254);

  doc.roundedRect(
    15,
    y,
    180,
    25,
    4,
    4,
    "F"
  );

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");

  doc.text(
    `ATS Score : ${result.similarity_score}%`,
    105,
    y + 15,
    {
      align: "center",
    }
  );

  y += 40;

  // ==========================
  // Matched Skills
  // ==========================

  doc.setFontSize(15);

  doc.text(
    "Matched Skills",
    15,
    y
  );

  autoTable(doc, {
    startY: y + 5,
    head: [["Skill"]],
    body: result.matched_skills.map(skill => [skill]),
    headStyles: {
      fillColor: [34, 197, 94],
    },
  });

  y = doc.lastAutoTable.finalY + 12;

  // ==========================
  // Missing Skills
  // ==========================

  doc.setFontSize(15);

  doc.text(
    "Missing Skills",
    15,
    y
  );

  autoTable(doc, {
    startY: y + 5,
    head: [["Skill"]],
    body: result.missing_skills.map(skill => [skill]),
    headStyles: {
      fillColor: [239, 68, 68],
    },
  });

  y = doc.lastAutoTable.finalY + 15;

  // ==========================
  // New Page
  // ==========================

  doc.addPage();

  y = 20;

  // ==========================
  // Overall Feedback
  // ==========================

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");

  doc.text(
    "Overall Feedback",
    15,
    y
  );

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  let feedback = doc.splitTextToSize(
    result.overall_feedback,
    180
  );

  doc.text(
    feedback,
    15,
    y
  );

  y += feedback.length * 7 + 10;

  // ==========================
  // Strengths
  // ==========================

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  doc.text(
    "Strengths",
    15,
    y
  );

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  result.strengths.forEach(item => {
    doc.text(
      `• ${item}`,
      20,
      y
    );
    y += 7;
  });

  y += 8;

  // ==========================
  // Weaknesses
  // ==========================

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  doc.text(
    "Weaknesses",
    15,
    y
  );

  y += 8;

  doc.setFont("helvetica", "normal");

  result.weaknesses.forEach(item => {
    doc.text(
      `• ${item}`,
      20,
      y
    );
    y += 7;
  });

  y += 8;

  // ==========================
  // Resume Improvements
  // ==========================

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  doc.text(
    "Resume Improvements",
    15,
    y
  );

  y += 8;

  doc.setFont("helvetica", "normal");

  result.resume_improvements.forEach(item => {
    doc.text(
      `• ${item}`,
      20,
      y
    );
    y += 7;
  });

  y += 8;

  // ==========================
  // Interview Questions
  // ==========================

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");

  doc.text(
    "Interview Questions",
    15,
    y
  );

  y += 8;

  doc.setFont("helvetica", "normal");

  result.interview_questions.forEach(
    (item, index) => {
      let lines = doc.splitTextToSize(
        `${index + 1}. ${item}`,
        175
      );

      doc.text(
        lines,
        20,
        y
      );

      y += lines.length * 7;
    }
  );

  // ==========================
  // Footer
  // ==========================

  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {

    doc.setPage(i);

    const pageHeight =
      doc.internal.pageSize.height;

    doc.setDrawColor(200);

    doc.line(
      15,
      pageHeight - 18,
      195,
      pageHeight - 18
    );

    doc.setFontSize(10);

    doc.text(
      "Generated by AI Resume Analyzer",
      15,
      pageHeight - 10
    );

    doc.text(
      `Page ${i} of ${totalPages}`,
      195,
      pageHeight - 10,
      {
        align: "right",
      }
    );
  }

  doc.save("AI_Resume_Report.pdf");
}